version: "3"

services:
  node:
     build: ./backend
     depends_on:
       - sql
     env_file:
        - ./docker-compose-lesson.env
     environment:
        - MYSQL_HOST=sql
     ports:
        - 8080:4200
     volumes:
        - ./backend/src:/home/node/app/src
        - ./backend/utils:/home/node/app/utils
        - ./backend/tsconfig.json:/home/node/app/tsconfig.json
  nginx:
     build: ./frontend
     depends_on:
        - node
     volumes:
        - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf
     ports:
        - 80:80
  sql:
    build: ./sql
    env_file:
       - ./docker-compose-lesson.env
    command: --default-authentication-plugin=mysql_native_password
    volumes:
     - compose-lesson:/var/lib/mysql
    ports:
       - 33006:3306
volumes:
  compose-lesson: